'use client';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { motion, useScroll } from 'framer-motion';
import { ArrowUpRight, Check } from 'lucide-react';
import ProgramDialog from './components/ProgramDialog';
import AcademySections from './components/AcademySections';
import ReferenceHero, { AcademyHeader } from './components/ReferenceHero';
import { Brand, Button, Label } from './components/AcademyUI';

export default function Home(){
 const [program,setProgram]=useState<string|null>(null); const {scrollYProgress}=useScroll();
 useEffect(()=>{const update=()=>document.querySelector('header')?.classList.toggle('scrolled',scrollY>30);update();window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update)},[]);
 return <><motion.div className="scroll-progress" style={{scaleX:scrollYProgress}}/><AcademyHeader/><main><ReferenceHero/>
 <section id="about" className="section about-section"><div className="about-image"><Image src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=85" fill sizes="(max-width:760px) 100vw, 45vw" alt="Collaborative learning session — illustrative photograph"/><div className="image-label">Small steps in class.<br/><strong>Meaningful steps forward.</strong></div></div><div><Label>WELCOME TO NXT ACADEMY</Label><h2>More than a classroom.<br/><em>A place to grow.</em></h2><p>NXT Academy of Creative Studies helps students build practical skills, confidence and professional readiness through career-focused training in Hospitality and Aviation.</p><p>From finding your voice to putting new skills into practice, your growth is at the heart of the learning experience.</p><a className="text-link" href="#why-nxt">Get to know NXT<ArrowUpRight size={18}/></a></div></section>
 <section id="courses" className="section courses-section"><div className="section-heading"><div><Label>OUR PROGRAMS</Label><h2>Choose your <em>career path.</em></h2></div><p>Find a direction that interests you.<br/>Build the skills to take it forward.</p></div><div className="course-grid">{[{name:'Hospitality',tag:'SERVICE. COMMUNICATION. CONFIDENCE.',description:'Build communication, service excellence, guest relations and professional hospitality skills.',skills:['Guest relations','Service skills','Practical learning'],image:'photo-1522071820081-009f0129c71c'},{name:'Aviation',tag:'SKILLS. PRESENTATION. READINESS.',description:'Develop confidence, communication, grooming and aviation-focused professional skills.',skills:['Communication','Professional grooming','Industry skills'],image:'photo-1523240795612-9a054b0db644'}].map((c,i)=><article className="course-card" key={c.name}><div className="course-image"><Image src={`https://images.unsplash.com/${c.image}?auto=format&fit=crop&w=1100&q=85`} fill sizes="(max-width:760px) 100vw, 45vw" alt={`${c.name} learning concept — illustrative student photograph`}/><span>COURSE 0{i+1}</span></div><div className="course-body"><small>{c.tag}</small><h3>{c.name}</h3><p>{c.description}</p><div className="course-skills">{c.skills.map(s=><span key={s}><Check size={13}/>{s}</span>)}</div><button onClick={()=>setProgram(c.name.toUpperCase())}>Explore {c.name}<ArrowUpRight size={21}/></button></div></article>)}</div><p className="course-footnote">For SSLC & PUC students. Speak to admissions for eligibility, fees, duration and the next intake.</p></section>
 <AcademySections/></main><footer><div className="footer-main"><div><Brand/><p>NXT Academy of Creative Studies<br/>Mangaluru, Karnataka</p><span>Practical learning. Professional growth.</span></div><div><h3>Explore NXT</h3>{['About','Courses','Why NXT','Student Life'].map(n=><a href={'#'+n.toLowerCase().replace(' ','-')} key={n}>{n}</a>)}</div><div><h3>Your next step</h3><a href="#courses">Hospitality training</a><a href="#courses">Aviation training</a><a href="#admissions">Admissions</a><a href="#contact">Contact us</a></div><div><h3>Let’s connect</h3><a href="tel:+918217337597">+91 821 733 7597</a><a href="mailto:nxtacademy69@gmail.com">nxtacademy69@gmail.com</a><a href="https://wa.me/918217337597" target="_blank" rel="noopener noreferrer">Chat on WhatsApp ↗</a><small>Instagram · Facebook · YouTube<br/>Official profiles coming soon.</small></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} NXT Academy of Creative Studies</span><span>Learn with purpose. Grow with confidence.</span></div></footer><ProgramDialog program={program} onClose={()=>setProgram(null)}/></>
}
