'use client';
import Image from 'next/image';
import { useState } from 'react';
import { ArrowUpRight, Plane, Hotel, GraduationCap, BookOpen, Users, MessageCircle, Phone, Plus, Minus, Check, Compass } from 'lucide-react';
import ReferenceHero, { AcademyHeader } from './components/ReferenceHero';
import ProgramDialog from './components/ProgramDialog';
import { Brand } from './components/AcademyUI';
import { Contact } from './components/Experience';
import { faq, pathways, photos } from './content';
const advantages=[{title:'Practical Learning',text:'Learn through activity-based training and hands-on sessions.',detail:'Presentation practice, role play, group activities and practical demonstrations help you put your learning into action.'},{title:'Professional Development',text:'Build communication, confidence and professional presentation.',detail:'Develop your voice through communication sessions, professional grooming and opportunities to participate.'},{title:'Industry-Relevant Skills',text:'Build a foundation in service and industry-focused skills.',detail:'Explore guest relations, service excellence and professional communication through Hospitality and Aviation training.'},{title:'Career-Focused Approach',text:'Learn with a clear direction for your next professional step.',detail:'Talk with the admissions team about your interests and find the program that fits your educational background.'}];
export default function Home(){
 const [program,setProgram]=useState<string|null>(null);
 const [question,setQuestion]=useState<number|null>(null);
 const [advantage,setAdvantage]=useState<number|null>(null);
 return <><AcademyHeader/><main><ReferenceHero/>
 <div className="reference-content"><div className="content-main"><section id="about" className="academy-intro"><p className="intro-label">NXT Academy of Creative Studies</p><h2>Build practical skills and <span>professional confidence.</span> Take your next step with career-focused Hospitality and Aviation training in Mangaluru.</h2><p>For SSLC and PUC students ready to learn, practise and grow. From finding your voice to putting new skills into practice, your growth is at the heart of the NXT learning experience.</p><a href="#why-nxt" className="underlined-link">Know More <ArrowUpRight size={15}/></a></section>
 <section id="courses" className="compact-courses"><h2>Courses We Offer</h2><div className="compact-course-grid">{[{id:'BBA',title:'BBA in Aviation & Hospitality Management',icon:Plane,duration:'3 years',eligibility:'Open to students after 12th / PUC.'},{id:'DIPLOMA',title:'Diploma in Aviation & Hospitality Management',icon:Hotel,duration:'1 year',eligibility:'Open to students after 10th, 12th / PUC or a degree.'}].map(({id,title,icon:Icon,duration,eligibility})=><button key={id} className="compact-course" onClick={()=>setProgram(id)}><span className="course-symbol"><Icon size={29} strokeWidth={1.5}/></span><span><strong>{title}</strong><span className="course-duration">{duration}</span><small>{eligibility}</small><span className="placement-guarantee"><Check size={14}/>100% placement guaranteed</span><em>Explore course <ArrowUpRight size={13}/></em></span></button>)}</div><p className="course-note">Contact admissions for fees, curriculum and the next intake.</p><div className="course-guidance"><h3>Let’s find your next step.</h3><p>Explore your interests and get guidance on choosing your course.</p><a href="#contact" className="button">Find My Course <ArrowUpRight size={16}/></a></div></section>
 <section className="career-directions"><h2>Where Your Skills Can Take You</h2><p>Explore career directions in hospitality, aviation and service.</p><div className="career-grid">{[...new Set([...pathways.Hospitality,...pathways.Aviation])].map((p,i)=><div key={p}>{i<6?<Hotel size={23}/>:<Plane size={23}/>}<span>{p}</span></div>)}</div><p className="course-note">Both programs include a 100% placement guarantee.</p><p className="intro-closing">At NXT Academy, every new skill is a step forward.<br/><a href="#contact">Join us</a> and turn your interests into a professional foundation.</p></section></div>
 <aside className="academy-sidebar"><section><h2>The NXT Approach</h2><div className="approach-layout"><div className="approach-photo"><Image src="/academy-learning.webp" fill unoptimized sizes="180px" alt="Illustrative mentor and students collaborating"/><span aria-hidden="true">”</span></div><div><h3>More than a classroom. A place to grow.</h3><p>Our focus is on practical learning, communication and professional readiness.</p><p>We help students build a foundation through active participation, shared ideas and everyday practice.</p><p>Your next chapter starts with a willingness to learn.</p><strong className="approach-signature">Learn. Practice. Grow.</strong><small>NXT Academy of Creative Studies</small></div></div></section>
 <div className="admissions-note" id="admissions"><GraduationCap size={43}/><div><h3>Finished SSLC or PUC?</h3><p>Explore your next step with NXT. Contact admissions to confirm program requirements.</p><a href="#contact">Enquire now <ArrowUpRight size={14}/></a></div></div>
 <section className="useful-links"><h2>Useful Links</h2><div>{[{title:'Explore Courses',text:'Find your direction',href:'courses',icon:BookOpen},{title:'Student Life',text:'Learn, share and grow',href:'student-life',icon:Users},{title:'Admissions',text:'Talk to our team',href:'contact',icon:GraduationCap},{title:'Your Questions',text:'Find helpful answers',href:'faq',icon:MessageCircle}].map(({title,text,href,icon:Icon})=><a href={'#'+href} key={title}><Icon size={26}/><span><strong>{title}</strong><small>{text}</small></span></a>)}</div></section>
 <section className="vision"><h2>Learning with Purpose</h2><h3>Practical skills. A professional mindset.</h3><p>NXT combines activity-based learning with communication and professional development, helping students prepare for life beyond the classroom.</p><h2>Growing with Confidence</h2><p>Our focus is simple: help students learn, practise and develop the confidence to take their next step in Hospitality and Aviation.</p></section></aside></div>
 <section id="why-nxt" className="reference-advantages"><span className="section-kicker">The NXT Advantage</span><h2>Why Choose NXT Academy</h2><p>A learning experience built around the skills you need and the person you’re becoming.</p><div className="advantage-grid">{advantages.map((a,i)=><button key={a.title} className={advantage===i?'expanded':''} onClick={()=>setAdvantage(advantage===i?null:i)} aria-expanded={advantage===i} aria-controls={'advantage-'+i}><span className="advantage-number">0{i+1}</span><h3>{a.title}</h3><p>{a.text}</p><span className="advantage-more">{advantage===i?'Show less':'Click to know more'}{advantage===i?<Minus size={16}/>:<Plus size={16}/>}</span>{advantage===i&&<p className="advantage-detail" id={'advantage-'+i}>{a.detail}</p>}</button>)}</div></section>
 <section className="learning-highlights"><div><span className="section-kicker">The Learning Experience</span><h2>Confidence Comes with Practice</h2><p>Explore the activities that help turn learning into practical skills.</p></div><div className="highlight-grid">{[{title:'Communication & confidence',image:'/academy-learning.webp',text:'Present ideas, practise speaking and learn together.'},{title:'Service & professionalism',image:photos[1].src,text:'Build guest relations and professional service skills.'},{title:'Aviation & career readiness',image:photos[0].src,text:'Develop a foundation for your next professional step.'}].map(c=><article key={c.title}><div><Image src={c.image} fill unoptimized sizes="(max-width:700px) 90vw, 30vw" alt={c.title+' — illustrative imagery'}/></div><h3>{c.title}</h3><p>{c.text}</p></article>)}</div></section>
 <section id="faq" className="reference-faq"><div><h2>Frequently Asked Questions</h2>{faq.map((f,i)=><div className="faq-item" key={f.q}><h3><button aria-expanded={question===i} aria-controls={'answer-'+i} onClick={()=>setQuestion(question===i?null:i)}>{f.q}{question===i?<Minus size={18}/>:<Plus size={18}/>}</button></h3><div id={'answer-'+i} hidden={question!==i}><p>{f.a}</p></div></div>)}</div><div className="guidance-column"><div className="guidance-card"><Compass size={38}/><h2>Let’s Talk About Your Future</h2><p>Speak with our admissions team for guidance on courses, eligibility and your next step.</p><a className="button" href="#contact">Enquire Now <ArrowUpRight size={17}/></a></div><h3>Career-Focused Learning in Mangaluru</h3><p>NXT Academy of Creative Studies offers Hospitality and Aviation training with practical learning, communication and professional development at its heart.</p><a className="underlined-link" href="#about">Read More <ArrowUpRight size={15}/></a></div></section>
 <section id="student-life" className="reference-gallery"><h2>Life at NXT</h2><p>New skills. Shared experiences. A little more confidence, every day.</p><div className="media-grid">{[{title:'Learning Together',src:'/academy-learning.webp'},{title:'The Classroom',src:'/nxt-classroom-hero.webp'},{title:'Collaboration',src:photos[2].src},{title:'Aviation',src:photos[0].src},{title:'Hospitality',src:photos[1].src}].map(p=><a href="#contact" key={p.title}><Image src={p.src} fill unoptimized sizes="(max-width:700px) 70vw, 20vw" alt={p.title+' — illustrative imagery'}/><div><small>The NXT Experience</small><h3>{p.title}</h3><ArrowUpRight size={18}/></div></a>)}</div><small className="imagery-note">Illustrative learning and industry imagery.</small></section>
 <Contact/></main><footer className="reference-footer"><Brand/><p>NXT Academy of Creative Studies · Mangaluru, Karnataka</p><nav aria-label="Footer navigation">{[['Home','home'],['About NXT','about'],['Courses','courses'],['Why NXT','why-nxt'],['Student Life','student-life'],['Admissions','admissions'],['Contact','contact']].map(([text,id])=><a href={'#'+id} key={id}>{text}</a>)}</nav><div className="footer-contacts"><a href="tel:+918217337597"><Phone size={17}/>+91 821 733 7597</a><a href="mailto:nxtacademy69@gmail.com">nxtacademy69@gmail.com</a><a href="https://wa.me/918217337597?text=Hello%20NXT%20Academy%2C%20I%20would%20like%20to%20know%20more%20about%20your%20BBA%20and%20Diploma%20courses." target="_blank" rel="noopener noreferrer"><MessageCircle size={17}/>WhatsApp</a></div><div className="footer-bottom">© {new Date().getFullYear()} NXT Academy of Creative Studies. All rights reserved.</div></footer><a className="floating-contact" href="https://wa.me/918217337597?text=Hello%20NXT%20Academy%2C%20I%20would%20like%20to%20know%20more%20about%20your%20BBA%20and%20Diploma%20courses." target="_blank" rel="noopener noreferrer" aria-label="Chat with NXT Academy on WhatsApp"><MessageCircle size={23}/></a><ProgramDialog program={program} onClose={()=>setProgram(null)}/></>
}
