'use client';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { motion, useScroll } from 'framer-motion';
import { ArrowUpRight, ArrowRight, BookOpen, Users, GraduationCap, Check, Menu, X, MapPin } from 'lucide-react';
import ProgramDialog from './components/ProgramDialog';
import AcademySections from './components/AcademySections';
import { Brand, Button, Label } from './components/AcademyUI';

export default function Home(){
 const [menu,setMenu]=useState(false); const [program,setProgram]=useState<string|null>(null); const {scrollYProgress}=useScroll();
 useEffect(()=>{const update=()=>document.querySelector('header')?.classList.toggle('scrolled',scrollY>30);update();window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update)},[]);
 return <><motion.div className="scroll-progress" style={{scaleX:scrollYProgress}}/><div className="topbar"><span><MapPin size={13}/>Mangaluru, Karnataka</span><span>Your next step after SSLC & PUC <ArrowRight size={13}/></span><a href="tel:+918217337597">Admissions: +91 821 733 7597</a></div><header><Brand/><nav aria-label="Main navigation" className={menu?'open':''}>{['Home','About','Courses','Why NXT','Student Life','Admissions','Contact'].map(n=><a key={n} href={'#'+n.toLowerCase().replace(' ','-')} onClick={()=>setMenu(false)}>{n}</a>)}</nav><a className="nav-button" href="#contact">Enquire now<ArrowUpRight size={16}/></a><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header><main>
 <section id="home" className="academy-hero"><div className="hero-copy"><Label>YOUR FUTURE STARTS WITH LEARNING</Label><h1>{['Build skills.','Build confidence.','Build your future.'].map((line,i)=><span className="hero-line" key={line}><motion.span initial={{y:'105%'}} animate={{y:0}} transition={{duration:.8,delay:.1+i*.14,ease:[.22,1,.36,1]}}>{line}</motion.span></span>)}</h1><p>Career-focused Hospitality and Aviation training<br className="desktop-break"/> for SSLC and PUC students.</p><div className="hero-actions"><Button href="#courses">Explore courses</Button><Button secondary>Enquire now</Button></div><div className="hero-note"><span className="note-icon"><GraduationCap size={23}/></span><span>A place to learn. The confidence to grow.<small>NXT Academy of Creative Studies · Mangaluru</small></span></div></div><div className="hero-visual"><div className="photo-frame"><Image className="hero-photo" src="/academy-learning.webp" fill unoptimized sizes="(max-width:760px) 100vw, 50vw" alt="Illustrative scene of Indian students collaborating with a mentor in a classroom" priority/><span className="photo-caption">LEARNING TOGETHER. GROWING TOGETHER.</span></div><div className="learning-stamp"><BookOpen size={23}/><span>More than a course.<strong>A stronger start.</strong></span></div><div className="visual-tag"><span/> Learn. Practice. Grow.</div><span className="image-disclosure">Illustrative learning imagery · not actual campus photography</span></div></section>
 <section className="learning-strip" aria-label="Our learning approach">{[{icon:BookOpen,title:'Practical learning',text:'Build skills by doing.'},{icon:Users,title:'Industry-relevant skills',text:'Learning with a clear purpose.'},{icon:GraduationCap,title:'Professional development',text:'Confidence for your next step.'}].map(({icon:Icon,title,text})=><div key={title}><Icon size={27} strokeWidth={1.5}/><span><strong>{title}</strong><small>{text}</small></span><ArrowUpRight size={19}/></div>)}</section>
 <section id="about" className="section about-section"><div className="about-image"><Image src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=85" fill sizes="(max-width:760px) 100vw, 45vw" alt="Collaborative learning session — illustrative photograph"/><div className="image-label">Small steps in class.<br/><strong>Meaningful steps forward.</strong></div></div><div><Label>WELCOME TO NXT ACADEMY</Label><h2>More than a classroom.<br/><em>A place to grow.</em></h2><p>NXT Academy of Creative Studies helps students build practical skills, confidence and professional readiness through career-focused training in Hospitality and Aviation.</p><p>From finding your voice to putting new skills into practice, your growth is at the heart of the learning experience.</p><a className="text-link" href="#why-nxt">Get to know NXT<ArrowUpRight size={18}/></a></div></section>
 <section id="courses" className="section courses-section"><div className="section-heading"><div><Label>OUR PROGRAMS</Label><h2>Choose your <em>career path.</em></h2></div><p>Find a direction that interests you.<br/>Build the skills to take it forward.</p></div><div className="course-grid">{[{name:'Hospitality',tag:'SERVICE. COMMUNICATION. CONFIDENCE.',description:'Build communication, service excellence, guest relations and professional hospitality skills.',skills:['Guest relations','Service skills','Practical learning'],image:'photo-1522071820081-009f0129c71c'},{name:'Aviation',tag:'SKILLS. PRESENTATION. READINESS.',description:'Develop confidence, communication, grooming and aviation-focused professional skills.',skills:['Communication','Professional grooming','Industry skills'],image:'photo-1523240795612-9a054b0db644'}].map((c,i)=><article className="course-card" key={c.name}><div className="course-image"><Image src={`https://images.unsplash.com/${c.image}?auto=format&fit=crop&w=1100&q=85`} fill sizes="(max-width:760px) 100vw, 45vw" alt={`${c.name} learning concept — illustrative student photograph`}/><span>COURSE 0{i+1}</span></div><div className="course-body"><small>{c.tag}</small><h3>{c.name}</h3><p>{c.description}</p><div className="course-skills">{c.skills.map(s=><span key={s}><Check size={13}/>{s}</span>)}</div><button onClick={()=>setProgram(c.name.toUpperCase())}>Explore {c.name}<ArrowUpRight size={21}/></button></div></article>)}</div><p className="course-footnote">For SSLC & PUC students. Speak to admissions for eligibility, fees, duration and the next intake.</p></section>
 <AcademySections/></main><footer><div className="footer-main"><div><Brand/><p>NXT Academy of Creative Studies<br/>Mangaluru, Karnataka</p><span>Practical learning. Professional growth.</span></div><div><h3>Explore NXT</h3>{['About','Courses','Why NXT','Student Life'].map(n=><a href={'#'+n.toLowerCase().replace(' ','-')} key={n}>{n}</a>)}</div><div><h3>Your next step</h3><a href="#courses">Hospitality training</a><a href="#courses">Aviation training</a><a href="#admissions">Admissions</a><a href="#contact">Contact us</a></div><div><h3>Let’s connect</h3><a href="tel:+918217337597">+91 821 733 7597</a><a href="mailto:nxtacademy69@gmail.com">nxtacademy69@gmail.com</a><a href="https://wa.me/918217337597" target="_blank" rel="noopener noreferrer">Chat on WhatsApp ↗</a><small>Instagram · Facebook · YouTube<br/>Official profiles coming soon.</small></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} NXT Academy of Creative Studies</span><span>Learn with purpose. Grow with confidence.</span></div></footer><ProgramDialog program={program} onClose={()=>setProgram(null)}/></>
}
